Additional script tag options added
halloverden/ngx-cookiebot pull request #12
Opened 2023-03-01 12:31 UTC by wiseguy1394

I've added some more options for the script tag:
https://support.cookiebot.com/hc/en-us/articles/4406571299346-The-Cookiebot-CMP-widget#h_01FGB7S0AF7M41HJC8ZD83MA0F

2023-03-01 12:55 UTC, erichjsonfosse commented
Hi @wiseguy1394 !
Thanks for the PR!

It seems like this PR contains a lot of changes way beyond the scope of "Additional script tag options added". Could you scope it down a bit? :)

2023-03-01 13:01 UTC, wiseguy1394 commented
@erichjsonfosse ah..sry. I resetted changes which are not for the PR.

2023-03-01 13:52 UTC, erichjsonfosse requested changes
Thanks for contributing!
See comments :+1:

2023-03-01 13:52 UTC, erichjsonfosse commented on projects/ngx-cookiebot/src/lib/ngx-cookiebot.service.ts
> +      script.setAttribute('ddata-widget-distance-horizontal', this.cookiebotConfig.widgetDistanceHorizontal + '');
Typo in attribute name.

2023-03-01 13:52 UTC, erichjsonfosse commented on projects/ngx-cookiebot/src/lib/ngx-cookiebot.service.ts
> +      script.setAttribute('data-widget-distance-vertical', this.cookiebotConfig.widgetDistanceVertical + '');
Would prefer toString() instead of adding an empty string.

2023-03-01 16:26 UTC, erichjsonfosse approved these changes

2023-03-01 16:27 UTC, erichjsonfosse commented
@wiseguy1394 
Nice!
Thank you :)
We'll merge and publish a new version asap.

2023-03-02 14:28 UTC, merged

2023-03-02 14:47 UTC, erichjsonfosse commented
@wiseguy1394 
I've published an rc with the latest changes now (https://www.npmjs.com/package/@halloverden/ngx-cookiebot/v/2.1.0-rc.1). Could you test it and see if it is as you expect :)?

2023-03-03 09:22 UTC, wiseguy1394 commented
It works as expected. Thx. 👍🏻

2023-03-03 10:24 UTC, erichjsonfosse commented
Great!
New version published https://www.npmjs.com/package/@halloverden/ngx-cookiebot/v/2.2.0