update peerDependencies angular to support version 15.2
halloverden/ngx-cookiebot pull request #14
Opened 2023-03-14 11:53 UTC by davidgvf

2023-03-14 11:55 UTC, andreaslarssen requested changes

2023-03-14 11:55 UTC, andreaslarssen commented on projects/ngx-cookiebot/package.json
> +    "@angular/common": "8.2.14 - 15.2",
Could you target the major version?

2023-03-14 11:55 UTC, andreaslarssen commented on projects/ngx-cookiebot/package.json
> +    "@angular/core": "8.2.14 - 15.2"
Could you target the major version?

2023-03-14 11:59 UTC, davidgvf commented on projects/ngx-cookiebot/package.json
> +    "@angular/common": "8.2.14 - 15.2",
yes

2023-03-14 13:00 UTC, andreaslarssen commented
@davidgvf nice, did you test it?

2023-03-14 13:07 UTC, andreaslarssen commented
@davidgvf ok, will provide a release candidate for you to test as soon as I can

2023-03-15 07:22 UTC, davidestrim commented
@andreaslarssen when can you do it?

2023-03-15 07:23 UTC, andreaslarssen commented
> @andreaslarssen when can you do it?

This evening I was hoping

2023-03-15 19:31 UTC, merged

2023-03-15 19:39 UTC, andreaslarssen commented
@davidgvf The 2.3.0-rc.1 version is out. Try that and let me know if it looks good. I will also test it on my side, and I'll publish 2.3.0 after we've both verified

2023-03-15 19:59 UTC, andreaslarssen commented
@davidestrim / @davidgvf 2.3.0 is out