Upgrade library to use Angular 16 / Ivy
halloverden/ngx-cookiebot pull request #16
Opened 2023-05-12 12:33 UTC by JesseDeBruijne

- Update from Angular 8 -> Angular 16
- Switch from tslint to eslint and update some linting errors
- Repair unit tests with new Angular version
- Remove unused / old packages

Fixes https://github.com/halloverden/ngx-cookiebot/issues/9

2023-05-12 12:47 UTC, andreaslarssen commented
Nice! Will try and release as soon as I find a minute. Thanks!
PS! Have you tested the build as well?

2023-05-12 12:58 UTC, JesseDeBruijne commented
@andreaslarssen How can I test the build? I'm not very familiar with Docker if that's how you build it

2023-05-12 13:26 UTC, andreaslarssen commented
> @andreaslarssen How can I test the build? I'm not very familiar with Docker if that's how you build it

We don't use Docker for that, but no worries, I'll test it before releasing it, and it's a major version, so worst case we'll hear about it. Thanks again

2023-05-16 07:45 UTC, JesseDeBruijne commented
Hey @andreaslarssen 

I don't mean to sound impatient but I was wondering when you think you have some spare time to check and release these changes. I would love to update my libraries to Angular 16 and I'm sure many other users of this package would too :)

2023-05-16 07:52 UTC, andreaslarssen commented
@JesseDeBruijne i know, i'm really sorry that it takes some time. Will try and create an rc version for you to test as soon as i can.

2023-05-16 19:08 UTC, andreaslarssen commented
@JesseDeBruijne I changed the target branch so we can create a npm package and test it before merging to master

2023-05-16 19:11 UTC, andreaslarssen requested changes

2023-05-16 19:11 UTC, andreaslarssen commented on projects/ngx-cookiebot/package.json
> +    "@angular/core": "9 - 16"
If you're not able to test each version from 9-16, I suggest you change both these to  ^16.0.0, and we'll see later if we want to extend version support or release a new major when A17 comes around

2023-05-16 19:13 UTC, merged

2023-05-16 19:36 UTC, andreaslarssen commented
@JesseDeBruijne `3.0.0-rc.1` has been pushed. Could you install it and verify that it's good?

2023-05-16 19:36 UTC, andreaslarssen commented on projects/ngx-cookiebot/package.json
> +    "@angular/core": "9 - 16"
Fixed it after merging

2023-05-17 13:42 UTC, JesseDeBruijne commented
Hey @andreaslarssen 

I have installed the `3.0.0-rc.1` version in an Angular 16 app and it works just fine! The dialog opens as expected, no errors during building or in runtime.